[build]
  command = "npm run build"
  publish = "out"

[context.production.environment]
  NEXT_PUBLIC_GROQ_API_KEY = "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"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
